# Generated by Django 4.2.2 on 2023-06-09 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acquirente',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('via', models.CharField(max_length=20)),
                ('numCivico', models.CharField(max_length=20)),
                ('CAP', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Acquirenti',
            },
        ),
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('schedaTecnica', models.TextField()),
                ('immagine', models.CharField(max_length=20)),
                ('prezzoIniziale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prezzoRiserva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prezzoAttuale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dataInizioAsta', models.DateTimeField()),
                ('durataAsta', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Venditore',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('via', models.CharField(max_length=20)),
                ('numCivico', models.CharField(max_length=20)),
                ('CAP', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Venditori',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('voto', models.IntegerField()),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.acquirente')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.venditore')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.acquirente')),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.articolo')),
            ],
            options={
                'verbose_name_plural': 'Offerte',
            },
        ),
        migrations.AddField(
            model_name='articolo',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.venditore'),
        ),
    ]
