# Generated by Django 4.2.2 on 2023-06-16 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=20)),
                ('schedaTecnica', models.TextField()),
                ('immagine', models.CharField(max_length=20)),
                ('prezzoIniziale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prezzoRiserva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prezzoAttuale', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dataInizioAsta', models.DateTimeField()),
                ('durataAsta', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Articoli',
            },
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email:')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username:')),
                ('password', models.CharField(max_length=20, verbose_name='Password:')),
                ('is_venditore', models.BooleanField(default=False, verbose_name='Venditore:')),
            ],
            options={
                'verbose_name_plural': 'Utenti',
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('voto', models.IntegerField()),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquirente', to='gestione.utente')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venditore', to='gestione.utente')),
            ],
            options={
                'verbose_name_plural': 'Recensioni',
            },
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.utente')),
                ('articolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.articolo')),
            ],
            options={
                'verbose_name_plural': 'Offerte',
            },
        ),
        migrations.AddField(
            model_name='articolo',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestione.utente'),
        ),
    ]
