# Generated by Django 4.2.2 on 2023-06-17 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='acquirente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='acquirente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquirente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='venditore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venditore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Utente',
        ),
    ]
