# Generated by Django 4.2.2 on 2023-06-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_alter_articolo_venditore_alter_offerta_acquirente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='dataInizioAsta',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='venditore',
            field=models.CharField(max_length=20),
        ),
    ]
