# Generated by Django 4.2.2 on 2023-06-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0003_alter_articolo_datainizioasta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='prezzoAttuale',
        ),
        migrations.AddField(
            model_name='articolo',
            name='categoria',
            field=models.CharField(choices=[('Elettronica', 'Elettronica'), ('Informatica', 'Informatica'), ('CD e Vinili', 'CD e Vinili'), ('Videogiochi', 'Videogiochi'), ('Strumenti musicali', 'Strumenti musicali'), ('Film e DVD', 'Film e DVD')], default='Elettronica', max_length=20),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='immagine',
            field=models.ImageField(upload_to=None),
        ),
    ]
