# Generated by Django 4.2.2 on 2023-06-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_remove_articolo_prezzoattuale_articolo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='durataAsta',
            field=models.IntegerField(choices=[(12, 12), (24, 24), (48, 48), (72, 72)], default=12),
        ),
    ]
