# Generated by Django 4.2.2 on 2023-06-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0005_alter_articolo_durataasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='immagine',
            field=models.ImageField(upload_to='articoli/%Y/%m/'),
        ),
    ]
