# Generated by Django 4.2.2 on 2023-06-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_alter_articolo_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='immagine',
            field=models.ImageField(upload_to='articoli/'),
        ),
    ]
