# Generated by Django 4.2.2 on 2023-06-30 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0007_alter_articolo_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='dataFineAsta',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 13, 52, 13, 371523, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
