# Generated by Django 4.2.2 on 2023-07-01 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0009_articolo_terminato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articolo',
            name='prezzoRiserva',
        ),
        migrations.AlterField(
            model_name='articolo',
            name='prezzoIniziale',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
