# Generated by Django 4.2.2 on 2023-07-04 15:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0010_remove_articolo_prezzoriserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articolo',
            name='durataAsta',
            field=models.IntegerField(choices=[(12, 12), (24, 24), (48, 48), (72, 72), (96, 96), (120, 120), (144, 144)], default=12),
        ),
        migrations.AlterField(
            model_name='articolo',
            name='prezzoIniziale',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='offerta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='voto',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
